#!/bin/bash

############################################################
#
#
#
#    THE YOH PROJECT
#    --------------------------------------------------
#
#    Copyright 2013 JT Paasch
#    License MIT <http://opensource.org/licenses/MIT>
#
#
############################################################


# Get the heroku toolbelt.
wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh

# Exit cleanly.
exit 0
