#!/bin/bash

############################################################
#
#
#
#    THE YOH PROJECT
#    --------------------------------------------------
#
#    Copyright 2013 JT Paasch
#    License MIT <http://opensource.org/licenses/MIT>
#
#
############################################################


# Add the keys.
/usr/local/heroku/bin/heroku keys:add

# Exit cleanly
exit 0
